### ISSUE TITLE
静岡県では利用していないカードのimportを除去

### ISSUE THREAD

**Issue by hrsano645** [aktnk/covid19#50]
## 改善詳細 / Details of Improvement
- #46 から派生
- サイトのビルド(`yarn run generate:deploy`)中にスクリーンショットのようなエラーが起きる

この日のビルドの例: https://github.com/hiroyuki-ichikawa/covid19/runs/1506284023?check_suite_focus=true

```
Error:   /cards/details-of-confirmed-cases

TypeError: Cannot read property 'date' of undefined
    at a.data (5ba5625148dda201dc0d.js:1:523197)
    at /Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28667
    at /Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28727
    at pn (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28934)
    at a.e._init (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:32700)
    at new a (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
    at Vi (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:66369)
    at io (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70599)
    at ro (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at eo (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)
    at /Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70739
    at Yi (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67229)
    at io (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70641)
    at ro (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at eo (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)
    at /Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70739
Error:   /cards/details-of-tested-cases

TypeError: Cannot read property 'date' of undefined
    at a.data (5ba5625148dda201dc0d.js:1:523292)
    at /Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28667
    at /Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28727
    at pn (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28934)
    at a.e._init (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:32700)
    at new a (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
    at Vi (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:66369)
    at io (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70599)
    at ro (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at eo (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)
    at /Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70739
    at Yi (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67229)
    at io (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70641)
    at ro (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at eo (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)
    at /Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70739
Error:   /cards/number-of-inspection-persons

TypeError: Cannot read property 'date' of undefined
    at a.data (5ba5625148dda201dc0d.js:1:523631)
    at /Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28667
    at /Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28727
    at pn (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:28934)
    at a.e._init (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:32700)
    at new a (/Users/runner/work/covid19/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
    at Vi (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:66369)
    at io (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70599)
    at ro (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at eo (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)
    at /Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70739
    at Yi (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67229)
    at io (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70641)
    at ro (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at eo (/Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)
    at /Users/runner/work/covid19/covid19/node_modules/vue-server-renderer/build.prod.js:1:70739
Error:   /cards/number-of-reports-to-covid19-telephone-advisory-center

# 後略
```

改善としては、このエラーを除去したい。

利用していないカードをimportしている状況で、その時に参照する先のjsonのキーがないのが原因らしい

- @aktnk さんが除去のテストを行っていただいて、エラーを除去できることを確認
  - https://github.com/aktnk/covid19-test/commit/b143e1903d400420f657a030c5b64673d642033e

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/23502/101292280-d1e6c380-3851-11eb-8f17-24e8d4289e91.png)

## 期待する見せ方・挙動 / Expected behavior
- ビルド時のエラーを除去する

**Comment by hrsano645** [comment]
使っていないカードをimportするときのエラーだったようですが、このエラーログだけだと判断付きづらい😅
